### ISSUE TITLE
About quotes and escaping values

### ISSUE THREAD

**Issue by camilohollanda** [jcouture/nv#10]
NV will automatically escape INTEREST_NOTIFICATION_EMAILS value, but other tools don't do that.
This generates some incompatibility of the .env file format understood by nv.

```.env
INTEREST_NOTIFICATION_EMAILS=dev1@email.com|dev2@email.com
```

```.env
INTEREST_NOTIFICATION_EMAILS="dev1@email.com|dev2@email.com"
```

Is there some switch that makes nv understand if a value is already escaped or not?

**Comment by jcouture** [comment]
Thanks for reaching out.

In this example, should the value of `INTEREST_NOTIFICATION_EMAILS` be:

`dev1@email.com|dev2@email.com`

or

`"dev1@email.com|dev2@email.com"`

**Comment by camilohollanda** [comment]
Hey @jcouture thanks for answering this issue.

I was able to figure out a better way of loading env vars that would work with unscaped values, same way nv does.

I will leave it here:

```bash
export $(cat .env | sed 's/#.*//g' | xargs)
```
