### ISSUE TITLE
Please add the following troubleshooting section to the ReadMe

### ISSUE THREAD

**Issue by raphpap** [jcouture/nv#3]
## Troubleshooting

If after running a command with `nv`, such as

```
nv .env rails --version
```
you get the following error

```
unknown command: rails. Perhaps you have to reshim?
```

try adding the following to your `~/.nv` file.

```
HOME=/Users/<<your username>>
USER=<<your username>>
```

**Comment by jcouture** [comment]
Thanks!

Closing this issues as it's been addressed with PR #5.

Feel free to open another issue if needed.
