### ISSUE TITLE
`nv` breaks certain interactive TTY apps under tmux

### ISSUE THREAD

**Issue by carlpaten** [jcouture/nv#7]
```bash
$ nv .env less .env
WARNING: terminal is not fully functional
-  (press RETURN)
```

When you press RETURN `less` opens but you can't e.g. scroll with arrow keys.

I have no idea if this is worth fixing, but I guess it could be mentioned as a limitation in the README.

**Comment by jcouture** [comment]
Thanks for brining this behaviour to my attention.

What shell are you using? What is your operating system and architecture?

**Comment by carlpaten** [comment]
Bash, Ubuntu 20.10, x64.

**Comment by remi** [comment]
@lilred I was able to reproduce your bug by _removing_ the following line from me `~/.nv` global environment file:

```
TERM=xterm-color
```

With a valid `TERM` variable, `less` (or any TTY command) is working correctly.

@jcouture I think this would be a good usecase to add to the [**Troubleshooting**](https://github.com/jcouture/nv#troubleshooting) section 🙂

**Comment by carlpaten** [comment]
Interesting, the missing detail was that I was working inside of tmux, where `$TERM` is set to `screen`.

**Comment by remi** [comment]
> I was working inside of tmux, where $TERM is set to screen.

Yes, but when you’re using `nv`, the whole environment is cleared for the running command.

So if you don’t define `TERM` in either `~/.nv` or `.env`, `$TERM` is not defined when `less` is executed.

**Comment by carlpaten** [comment]
Makes sense, thanks!
